# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for android app distribution"
  lane :test do
  sh "flutter build apk --release"
    firebase_app_distribution(
      app: "1:209383179475:android:3af3d7ea167a346f88c026",
      firebase_cli_token:"1//03mB2cXwXgFw5CgYIARAAGAMSNwF-L9IrvjFn5fGj_CA1Gu25Y-4mlv-fWEsmpS4JFxi0-_aPvFHscvi1pkBB-GPUaUqdQQLY8FI",
     testers: "abwalshykhmhmd990@gmail.com",
     android_artifact_type:'APK',
     android_artifact_path:  "D:/qr_code/build/app/outputs/apk/release/app-release.apk",
     release_notes:"last version",

    )

  end

end
